const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f9fafb",
  },
  mainContent: {
    padding: "24px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "32px",
  },
  pageTitle: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#13274f",
    margin: 0,
  },
  headerIcons: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  headerIcon: {
    width: "24px",
    height: "24px",
    color: "#6b7280",
    cursor: "pointer",
    transition: "color 0.2s",
  },
  tabContainer: {
    display: "flex",
    gap: "8px",
    marginBottom: "24px",
  },
  tabButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tabIcon: {
    width: "16px",
    height: "16px",
  },
  tabButtonActive: {
    backgroundColor: "#13274f",
    color: "white",
  },
  tabButtonInactive: {
    backgroundColor: "white",
    color: "#6b7280",
    border: "1px solid #d1d5db",
  },
  searchBarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  searchInputWrapper: {
    position: "relative",
    flex: 1,
    maxWidth: "400px",
    minWidth: "300px",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "20px",
    height: "20px",
    color: "#9ca3af",
  },
  searchInput: {
    width: "100%",
    padding: "12px 12px 12px 40px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  btn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  btnIcon: {
    width: "16px",
    height: "16px",
  },
  btnSearch: {
    backgroundColor: "#13274f",
    color: "white",
  },
  btnAdd: {
    backgroundColor: "#fbbf24",
    color: "black",
    fontWeight: "600",
  },
  btnCancel: {
    backgroundColor: "transparent",
    color: "#6b7280",
    border: "1px solid #d1d5db",
  },
  btnSubmit: {
    backgroundColor: "#13274f",
    color: "white",
  },
  btnDestructive: {
    backgroundColor: "#dc2626",
    color: "white",
  },
  btnOutline: {
    backgroundColor: "white",
    color: "#6b7280",
    border: "1px solid #d1d5db",
  },
  btnGhost: {
    backgroundColor: "transparent",
    color: "#6b7280",
  },
  contentArea: {
    backgroundColor: "#f9fafb",
    padding: "24px",
    minHeight: "calc(100vh - 200px)",
    position: "relative",
  },
  backgroundWatermark: {
    position: "absolute",
    top: "80px",
    left: "80px",
    fontSize: "4rem",
    fontWeight: "bold",
    color: "rgba(107, 114, 128, 0.05)",
    transform: "rotate(12deg)",
    pointerEvents: "none",
    zIndex: 1,
  },
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    padding: "24px",
    border: "1px solid #e5e7eb",
    position: "relative",
  },
  cardGrid: {
    display: "grid",
    gap: "24px",
  },
  cardGrid2: {
    gridTemplateColumns: "1fr 1fr",
  },
  cardGrid4: {
    gridTemplateColumns: "repeat(4, 1fr)",
  },
  imageContainer: {
    backgroundColor: "#f3f4f6",
    borderRadius: "8px",
    padding: "16px",
    height: "320px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  imageContainerSmall: {
    backgroundColor: "#f3f4f6",
    borderRadius: "8px",
    height: "128px",
    marginBottom: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
  },
  addNewCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "24px",
    border: "2px dashed #d1d5db",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "border-color 0.2s",
    height: "100%",
  },
  addNewCardHover: {
    borderColor: "#9ca3af",
  },
  addIcon: {
    width: "48px",
    height: "48px",
    color: "#9ca3af",
    marginBottom: "16px",
  },
  addIconSmall: {
    width: "32px",
    height: "32px",
    color: "#9ca3af",
  },
  addText: {
    color: "#6b7280",
    fontSize: "18px",
  },
  addTextSmall: {
    color: "#6b7280",
    fontSize: "14px",
  },
  personCard: {
    backgroundColor: "#f9fafb",
    borderRadius: "8px",
    padding: "16px",
    textAlign: "center",
    position: "relative",
  },
  personImage: {
    width: "64px",
    height: "64px",
    backgroundColor: "#e5e7eb",
    borderRadius: "50%",
    margin: "0 auto 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  personName: {
    fontWeight: "500",
    fontSize: "14px",
    marginBottom: "4px",
    color: "#111827",
  },
  personTitle: {
    fontSize: "12px",
    color: "#6b7280",
  },
  actionButtons: {
    position: "absolute",
    top: "8px",
    right: "8px",
    display: "flex",
    gap: "4px",
    opacity: 0,
    transition: "opacity 0.2s",
  },
  actionButtonsVisible: {
    opacity: 1,
  },
  actionButton: {
    width: "28px",
    height: "28px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "500px",
    maxHeight: "90vh",
    overflowY: "auto",
    padding: "15px"
  },
  modalHeader: {
    padding: "24px 24px 0 24px",
    borderBottom: "1px solid #e5e7eb",
    marginBottom: "24px",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#13274f",
    margin: 0,
  },
  modalForm: {
    padding: "0 24px 24px 24px",
  },
  formGroup: {
    marginBottom: "20px",
  },
  formLabel: {
    display: "block",
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    marginBottom: "6px",
  },
  formInput: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    paddingTop: "16px",
    borderTop: "1px solid #e5e7eb",
    marginTop: "24px",
  },
  dropdownContainer: {
    position: "relative",
  },
  dropdownContent: {
    position: "absolute",
    top: "100%",
    left: 0,
    zIndex: 10,
    marginTop: "8px",
    width: "224px",
    borderRadius: "6px",
    boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    backgroundColor: "white",
    border: "1px solid rgba(0, 0, 0, 0.05)",
  },
  dropdownItem: {
    display: "block",
    padding: "16px",
    fontSize: "14px",
    color: "#374151",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  dropdownItemHover: {
    backgroundColor: "#f3f4f6",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#13274f",
    marginBottom: "24px",
  },
  contactGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "32px",
  },
  contactSection: {
    marginBottom: "16px",
  },
  contactLabel: {
    fontWeight: "500",
    color: "#111827",
    marginBottom: "4px",
  },
  contactText: {
    color: "#6b7280",
    lineHeight: "1.5",
  },
  scheduleItem: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
}

export default styles
