const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f9fafb",
  },
  mainContent: {
    padding: "24px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "32px",
  },
  pageTitle: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#13274f",
    margin: 0,
  },
  headerIcons: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  headerIcon: {
    width: "24px",
    height: "24px",
    color: "#6b7280",
    cursor: "pointer",
    transition: "color 0.2s",
  },
  tabContainer: {
    display: "flex",
    gap: "8px",
    marginBottom: "24px",
  },
  tabButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tabIcon: {
    width: "16px",
    height: "16px",
  },
  tabButtonActive: {
    backgroundColor: "#13274f",
    color: "white",
  },
  tabButtonInactive: {
    backgroundColor: "white",
    color: "#6b7280",
    border: "1px solid #d1d5db",
  },
  searchBarContainer: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  searchInputWrapper: {
    position: "relative",
    flex: 1,
    maxWidth: "400px",
    minWidth: "300px",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "20px",
    height: "20px",
    color: "#9ca3af",
  },
  searchInput: {
    width: "100%",
    padding: "12px 12px 12px 40px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  btn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  btnIcon: {
    width: "16px",
    height: "16px",
  },
  btnSearch: {
    backgroundColor: "#13274f",
    color: "white",
  },
  btnAdd: {
    backgroundColor: "#fbbf24",
    color: "black",
    fontWeight: "600",
  },
  itemsList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  itemCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    padding: "24px",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    border: "1px solid #e5e7eb",
  },
  itemContent: {
    flex: 1,
  },
  itemHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
  },
  questionNumber: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    backgroundColor: "#13274f",
    color: "white",
    borderRadius: "50%",
    fontSize: "14px",
    fontWeight: "600",
    flexShrink: 0,
  },
  questionNumberText: {
    fontSize: "14px",
    fontWeight: "600",
  },
  feedbackIcon: {
    width: "16px",
    height: "16px",
  },
  itemDetails: {
    flex: 1,
  },
  itemTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#111827",
    margin: "0 0 8px 0",
    lineHeight: "1.4",
  },
  itemAnswer: {
    fontSize: "14px",
    color: "#6b7280",
    lineHeight: "1.5",
    margin: 0,
  },
  feedbackUrl: {
    fontSize: "14px",
    color: "#2563eb",
    textDecoration: "none",
    transition: "all 0.2s",
    wordBreak: "break-all",
  },
  itemActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginLeft: "16px",
  },
  actionBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
    border: "none",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "#6b7280",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  actionIcon: {
    width: "16px",
    height: "16px",
  },
  noResults: {
    textAlign: "center",
    padding: "48px 0",
  },
  noResultsText: {
    color: "#6b7280",
    fontSize: "18px",
    margin: 0,
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "600px",
    maxHeight: "90vh",
    overflowY: "auto",
    margin: "20px",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "24px 24px 0 24px",
    borderBottom: "1px solid #e5e7eb",
    marginBottom: "24px",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#13274f",
    margin: 0,
  },
  modalClose: {
    background: "none",
    border: "none",
    color: "#6b7280",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "6px",
    transition: "all 0.2s",
  },
  modalForm: {
    padding: "0 24px 24px 24px",
  },
  formGroup: {
    marginBottom: "20px",
  },
  formLabel: {
    display: "block",
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    marginBottom: "6px",
  },
  formInput: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  formTextarea: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
    resize: "vertical",
    minHeight: "60px",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    paddingTop: "16px",
    borderTop: "1px solid #e5e7eb",
    marginTop: "24px",
  },
  btnCancel: {
    backgroundColor: "transparent",
    color: "#6b7280",
    border: "1px solid #d1d5db",
  },
  btnSubmit: {
    backgroundColor: "#13274f",
    color: "white",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
  },
  loadingText: {
    color: "#6b7280",
    marginTop: "12px",
    fontSize: "14px",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  fieldHint: {
    fontSize: "12px",
    color: "#6b7280",
    marginTop: "4px",
    fontStyle: "italic",
  },
  faqTabGroup: {
    display: "flex",
    gap: "2px",
    backgroundColor: "#f3f4f6",
    borderRadius: "8px",
    padding: "2px",
  },
}


export default styles