const styles = {
    container: {
      minHeight: "100vh",
      backgroundColor: "#f9fafb",
    },
    mainContent: {
      padding: "24px",
    },
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: "32px",
    },
    pageTitle: {
      fontSize: "2rem",
      fontWeight: "bold",
      color: "#13274f",
      margin: 0,
    },
    headerIcons: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
    },
    headerIcon: {
      width: "24px",
      height: "24px",
      color: "#6b7280",
      cursor: "pointer",
      transition: "color 0.2s",
    },
    searchBarContainer: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
      marginBottom: "24px",
      flexWrap: "wrap",
    },
    searchInputWrapper: {
      position: "relative",
      flex: 1,
      maxWidth: "400px",
      minWidth: "300px",
    },
    searchIcon: {
      position: "absolute",
      left: "12px",
      top: "50%",
      transform: "translateY(-50%)",
      width: "20px",
      height: "20px",
      color: "#9ca3af",
    },
    searchInput: {
      width: "100%",
      padding: "12px 12px 12px 40px",
      border: "1px solid #d1d5db",
      borderRadius: "8px",
      fontSize: "14px",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box",
    },
    btn: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "12px 24px",
      border: "none",
      borderRadius: "8px",
      fontSize: "14px",
      fontWeight: "600",
      cursor: "pointer",
      transition: "all 0.2s",
      textDecoration: "none",
      whiteSpace: "nowrap",
    },
    btnIcon: {
      width: "16px",
      height: "16px",
    },
    btnSearch: {
      backgroundColor: "#13274f",
      color: "white",
    },
    btnFilter: {
      backgroundColor: "transparent",
      color: "#13274f",
      border: "1px solid #13274f",
    },
    btnAdd: {
      backgroundColor: "#fbbf24",
      color: "black",
      fontWeight: "600",
    },
    datesList: {
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    dateItem: {
      backgroundColor: "white",
      borderRadius: "8px",
      boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
      padding: "24px",
      transition: "all 0.2s",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      position: "relative",
      cursor: "default",
    },
    dateItemClickable: {
      cursor: "pointer",
    },
    dateItemDragging: {
      opacity: 0.5,
      transform: "rotate(5deg)",
    },
    dateItemDragOver: {
      borderTop: "3px solid #13274f",
      marginTop: "3px",
    },
    dragHandleArea: {
      position: "absolute",
      left: "0",
      top: "0",
      bottom: "0",
      width: "40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "grab",
      borderRadius: "8px 0 0 8px",
      transition: "background-color 0.2s",
    },
    dragHandleAreaHover: {
      backgroundColor: "rgba(19, 39, 79, 0.05)",
    },
    dragHandle: {
      color: "#9ca3af",
      transition: "color 0.2s",
    },
    dragHandleActive: {
      cursor: "grabbing",
      color: "#13274f",
    },
    dateContent: {
      flex: 1,
      marginLeft: "48px",
    },
    dateTitle: {
      fontSize: "18px",
      fontWeight: "600",
      color: "#111827",
      margin: "0 0 12px 0",
    },
    dateDetails: {
      display: "flex",
      alignItems: "center",
      gap: "24px",
      color: "#6b7280",
      flexWrap: "wrap",
    },
    dateInfo: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    infoIcon: {
      width: "16px",
      height: "16px",
    },
    infoText: {
      fontSize: "14px",
    },
    pdfIndicator: {
      display: "flex",
      alignItems: "center",
      gap: "4px",
      backgroundColor: "#dbeafe",
      color: "#1e40af",
      padding: "4px 8px",
      borderRadius: "4px",
      fontSize: "12px",
      fontWeight: "500",
    },
    dateActions: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      marginLeft: "16px",
    },
    actionBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "36px",
      height: "36px",
      border: "none",
      borderRadius: "6px",
      backgroundColor: "transparent",
      color: "#6b7280",
      cursor: "pointer",
      transition: "all 0.2s",
    },
    actionIcon: {
      width: "16px",
      height: "16px",
    },
    noResults: {
      textAlign: "center",
      padding: "48px 0",
    },
    noResultsText: {
      color: "#6b7280",
      fontSize: "18px",
      margin: 0,
    },
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1000,
    },
    modalContent: {
      backgroundColor: "white",
      borderRadius: "12px",
      width: "100%",
      maxWidth: "500px",
      maxHeight: "90vh",
      overflowY: "auto",
      margin: "20px",
    },
    viewModalContent: {
      backgroundColor: "white",
      borderRadius: "12px",
      width: "100%",
      maxWidth: "800px",
      maxHeight: "90vh",
      overflowY: "auto",
      margin: "20px",
    },
    modalHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "24px 24px 0 24px",
      borderBottom: "1px solid #e5e7eb",
      marginBottom: "24px",
    },
    modalTitle: {
      fontSize: "20px",
      fontWeight: "600",
      color: "#13274f",
      margin: 0,
    },
    modalClose: {
      background: "none",
      border: "none",
      fontSize: "24px",
      color: "#6b7280",
      cursor: "pointer",
      padding: 0,
      width: "32px",
      height: "32px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "6px",
      transition: "all 0.2s",
    },
    modalForm: {
      padding: "0 24px 24px 24px",
    },
    formGroup: {
      marginBottom: "20px",
    },
    formRow: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "16px",
    },
    formLabel: {
      display: "block",
      fontSize: "14px",
      fontWeight: "500",
      color: "#374151",
      marginBottom: "6px",
    },
    formInput: {
      width: "100%",
      padding: "10px 12px",
      border: "1px solid #d1d5db",
      borderRadius: "6px",
      fontSize: "14px",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box",
    },
    formTextarea: {
      width: "100%",
      padding: "10px 12px",
      border: "1px solid #d1d5db",
      borderRadius: "6px",
      fontSize: "14px",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box",
      resize: "vertical",
      minHeight: "80px",
    },
    fileUploadArea: {
      border: "2px dashed #d1d5db",
      borderRadius: "8px",
      padding: "24px",
      textAlign: "center",
      backgroundColor: "#f9fafb",
      transition: "all 0.2s",
      cursor: "pointer",
    },
    fileUploadAreaHover: {
      borderColor: "#13274f",
      backgroundColor: "#f0f4ff",
    },
    fileUploadText: {
      color: "#6b7280",
      fontSize: "14px",
      margin: "8px 0 0 0",
    },
    fileSelected: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "12px",
      backgroundColor: "#f0f9ff",
      border: "1px solid #0ea5e9",
      borderRadius: "6px",
      marginTop: "8px",
    },
    fileInfo: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      color: "#0369a1",
      fontSize: "14px",
    },
    removeFileBtn: {
      background: "none",
      border: "none",
      color: "#ef4444",
      cursor: "pointer",
      padding: "4px",
      borderRadius: "4px",
      transition: "background-color 0.2s",
    },
    modalActions: {
      display: "flex",
      justifyContent: "flex-end",
      gap: "12px",
      paddingTop: "16px",
      borderTop: "1px solid #e5e7eb",
      marginTop: "24px",
    },
    btnCancel: {
      backgroundColor: "transparent",
      color: "#6b7280",
      border: "1px solid #d1d5db",
    },
    btnSubmit: {
      backgroundColor: "#13274f",
      color: "white",
    },
    filterSection: {
      display: "flex",
      alignItems: "center",
      gap: "12px",
      marginBottom: "16px",
      padding: "16px",
      backgroundColor: "#f8fafc",
      borderRadius: "8px",
      border: "1px solid #e2e8f0",
    },
    filterLabel: {
      fontSize: "14px",
      fontWeight: "500",
      color: "#374151",
      minWidth: "80px",
    },
    filterInput: {
      padding: "8px 12px",
      border: "1px solid #d1d5db",
      borderRadius: "6px",
      fontSize: "14px",
      outline: "none",
      transition: "border-color 0.2s",
    },
    clearFiltersBtn: {
      backgroundColor: "#ef4444",
      color: "white",
      padding: "8px 16px",
      fontSize: "12px",
    },
    viewContent: {
      padding: "0 24px 24px 24px",
    },
    viewSection: {
      marginBottom: "24px",
    },
    viewSectionTitle: {
      fontSize: "16px",
      fontWeight: "600",
      color: "#374151",
      marginBottom: "8px",
    },
    viewSectionContent: {
      fontSize: "14px",
      color: "#6b7280",
      lineHeight: "1.5",
    },
    pdfViewer: {
      width: "100%",
      height: "400px",
      border: "1px solid #d1d5db",
      borderRadius: "8px",
    },
    noPdfMessage: {
      textAlign: "center",
      padding: "40px",
      color: "#9ca3af",
      backgroundColor: "#f9fafb",
      borderRadius: "8px",
      border: "1px dashed #d1d5db",
    },
    pdfHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "12px",
    },
    downloadBtn: {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      padding: "6px 12px",
      backgroundColor: "#1e40af",
      color: "white",
      borderRadius: "6px",
      fontSize: "12px",
      fontWeight: "500",
      cursor: "pointer",
      border: "none",
      transition: "background-color 0.2s",
    },
    loadingContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "40px",
      backgroundColor: "#f9fafb",
      borderRadius: "8px",
      border: "1px dashed #d1d5db",
    },
    loadingText: {
      color: "#6b7280",
      marginTop: "12px",
      fontSize: "14px",
    },
    loadingSpinner: {
      animation: "spin 1s linear infinite",
      color: "#13274f",
    },
    "@keyframes spin": {
      "0%": { transform: "rotate(0deg)" },
      "100%": { transform: "rotate(360deg)" },
    },
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(255, 255, 255, 0.8)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 2000,
    }
}

export default styles;

