const styles = {
  container: {
    padding: "20px",
    backgroundColor: "#f8f9fc",
    minHeight: "95vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "16px",
    marginBottom: "20px",
    backgroundColor: "#ffffff",
  },
  heading: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#13274f",
    margin: 0,
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "24px",
  },
  card: {
    position: "relative",
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    cursor: "pointer",
    height: "19rem",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  imageWrapper: {
    position: "relative",
    height: "80rem",
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  overlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "12px",
    opacity: 0,
    transition: "opacity 0.3s ease",
  },
  overlayVisible: {
    opacity: 1,
  },
  overlayButton: {
    padding: "10px 16px",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: "500",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    border: "none",
  },
  editButton: {
    backgroundColor: "#ffffff",
    color: "#2d3748",
  },
  deleteButton: {
    backgroundColor: "#e53e3e",
    color: "#ffffff",
  },
  newsTitle: {
    display: "-webkit-box",         
    alignItems: "center",       
    justifyContent: "center",   
    fontWeight: "600",
    fontSize: "1rem",
    color: "#2d3748",
    textAlign: "center",
    padding: "0.5rem",              
    overflow: "hidden",             
    textOverflow: "ellipsis",       
    WebkitLineClamp: 2,             
    WebkitBoxOrient: "vertical",    
    lineHeight: "1.2",              
    margin: "0 auto",               
    width: "100%",                  
    height: "80%"
  },
  addCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    border: "2px dashed #a0aec0",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "19rem",
    transition: "border-color 0.3s ease",
  },
  addCardHover: {
    borderColor: "#4a5568",
    color: "#2d3748",
  },
  addIconWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "64px",
    height: "64px",
    backgroundColor: "#edf2f7",
    borderRadius: "50%",
    marginBottom: "16px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "white",
    borderRadius: "12px",
    width: "90%",
    maxWidth: "500px",
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #e2e8f0",
  },
  modalTitle: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#13274f",
    margin: 0,
  },
  closeButton: {
    background: "none",
    border: "none",
    fontSize: "1.2rem",
    cursor: "pointer",
    color: "#6b7280",
    padding: "4px",
  },
  modalContent: {
    padding: "20px",
  },
  inputGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: "600",
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "1rem",
    boxSizing: "border-box",
  },
  fileInput: {
    width: "100%",
    padding: "8px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "1rem",
    boxSizing: "border-box",
  },
  currentImage: {
    width: "100%",
    maxHeight: "200px",
    objectFit: "cover",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
  },
  preview: {
    padding: "12px",
    backgroundColor: "#f3f4f6",
    borderRadius: "8px",
    fontSize: "0.875rem",
    color: "#6b7280",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    padding: "20px",
    borderTop: "1px solid #e2e8f0",
  },
  cancelButton: {
    padding: "10px 20px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    backgroundColor: "white",
    color: "#374151",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
  saveButton: {
    padding: "10px 20px",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#fbbf24",
    color: "black",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
}

export default styles;